# -*- coding: utf-8 -*-
"""annotation_count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJFKRqAG9IKgSgkKoa6aqJBi9beaNrKm
"""

import json

# Load exported Prodigy data
from google.colab import files
uploaded = files.upload()

# Path to the exported Prodigy JSONL file
input_file = "ner_dataset.jsonl"

# Initialize counters
relation_count = 0
relation_types = {}

# Parse the file and count relations
with open(input_file, "r", encoding="utf-8") as file:
    for line in file:
        data = json.loads(line)
        if "spans" in data:
            for span in data["spans"]:
                # Count only relation spans (if labeled this way)
                if "label" in span:
                    relation_count += 1
                    label = span["label"]
                    relation_types[label] = relation_types.get(label, 0) + 1

# Output results
print(f"Total Relations: {relation_count}")
print("Relation Type Counts:")
for label, count in relation_types.items():
    print(f" - {label}: {count}")

import json

# Load exported Prodigy data
from google.colab import files
uploaded = files.upload()

# Path to the exported Prodigy JSONL file
input_file = "10001.jsonl"

# Initialize counters
relation_count = 0
relation_types = {}

# Parse the file and count relations
with open(input_file, "r", encoding="utf-8") as file:
    for line in file:
        data = json.loads(line)
        if "spans" in data:
            for span in data["spans"]:
                # Count only relation spans (if labeled this way)
                if "label" in span:
                    relation_count += 1
                    label = span["label"]
                    relation_types[label] = relation_types.get(label, 0) + 1

# Output results
print(f"Total Relations: {relation_count}")
print("Relation Type Counts:")
for label, count in relation_types.items():
    print(f" - {label}: {count}")

import json

# Load exported Prodigy data
from google.colab import files
uploaded = files.upload()

# Path to the exported Prodigy JSONL file
input_file = "data_relations_utf8.jsonl"

# Initialize counters
relation_count = 0
relation_types = {}

# Parse the file and count relations
with open(input_file, "r", encoding="utf-8") as file:
    for line in file:
        data = json.loads(line)
        if "spans" in data:
            for span in data["spans"]:
                # Count only relation spans (if labeled this way)
                if "label" in span:
                    relation_count += 1
                    label = span["label"]
                    relation_types[label] = relation_types.get(label, 0) + 1

# Output results
print(f"Total Relations: {relation_count}")
print("Relation Type Counts:")
for label, count in relation_types.items():
    print(f" - {label}: {count}")